### ISSUE TITLE
PROBLEM WHEN RUN INSTALL

### ISSUE THREAD

**Issue by teodm** [qwertqwertzuzu/discord-mass-dm-tool#1]
I have this when I'll run the command
![Immagine](https://github.com/qwertqwertzuzu/discord-mass-dm/assets/143551450/52d4b511-4be2-4adf-9c38-31323ed71d15)

**Comment by qwertqwertzuzu** [comment]
> I have this when I'll run the command ![Immagine](https://user-images.githubusercontent.com/143551450/264138958-52d4b511-4be2-4adf-9c38-31323ed71d15.png)

Should be fixed now

**Comment by teodm** [comment]
Have other error now
![Immagine](https://github.com/qwertqwertzuzu/discord-mass-dm/assets/143551450/a97e4aeb-fe1a-4c26-8ad8-2785ee8c0804)

**Comment by qwertqwertzuzu** [comment]
> Have other error now ![Immagine](https://user-images.githubusercontent.com/143551450/264148074-a97e4aeb-fe1a-4c26-8ad8-2785ee8c0804.png)

ok should be fixed now

**Comment by qwertqwertzuzu** [comment]
Does it work now for you?

**Comment by imuuid** [comment]
bro it's a logger 💀
